# fly.toml app configuration file generated for spend-sync on 2023-05-16T07:23:29+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "spend-sync"
primary_region = "lhr"
kill_signal = "SIGTERM"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "spend-sync.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
